language: java

sudo: false

jdk:
  - openjdk11

branches:
  only:
    - java11

deploy:
  branches:
    only:
      - java11
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
